package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "networkit",
    srcs = ["libnetworkit.a"],
    includes = ["include"],
    deps = ["//tlx:tlx", "//ttmath:ttmath"]
)